name: CI

on:
  push:

jobs:
      
  Build-Solution:
    runs-on: windows-2022
    steps:

    - name: Setup .NET Core SDK 8.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI Workloads
      run: dotnet workload install android ios maui-android maui-ios --ignore-failed-sources

    - uses: actions/checkout@v1
    - name: build
      run: ./build.sh