name: CI Build

on:
  push:

jobs:
      
  Android:
    runs-on: macos-latest
    steps:

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd Library
        msbuild /p:Configuration=Release RadarIO.Xamarin
        msbuild /p:Configuration=Release RadarIO.Xamarin.iOS
        msbuild /p:Configuration=Release RadarIO.Xamarin.Android
        nuget pack
        echo ${{ NUGET_API_KEY }}